[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "W", "C901"]
ignore = []

[tool.pyright]
include = ["."]
exclude = []
ignore = ["./features/steps/*.py"]
